# Association Rules Mining

    Nama : Briaan Putrantio
    NIM  : 0706022010021

# Association Rules

Association Rule Mining adalah salah satu metode data mining yang dapat mengidentifikasi hubungan kesamaan antar item. Dalam metode ini dibutuhkan algoritma untuk mencari kandidat aturan asosiasi.

Association Rules merupakan "if-then" statements, yang membantu menunjukkan kemungkinan hubungan antara item data, dalam kumpulan data besar di berbagai jenis database. Association Rule Mining memiliki sejumlah cara pengaplikasian dan digunakan secara luas untuk membantu menemukan korelasi penjualan dalam data transaksional atau dalam kumpulan data medis.

# Tujuan Association Rules Mining

Association Rules Mining bertujuan untuk menunjukkan nilai asosiatif antara jenis-jenis produk yang dibeli oleh pelanggan sehingga terlihatlah suatu pola berupa produk apa saja yang sering dibeli oleh pelanggan tersebut. Dengan mengetahui jenis produk yang sering dibeli maka dapat dibuat sebagai sebuah dasar keputusan untuk menentukan produk apa saja yang cocok untuk dipromosikan kepada pelanggan tersebut. Algoritma Apriori juga perlu dipergunakan untuk menentukan frequent itemset sehingga hasil akhir yang dicapai yaitu untuk menghitung persentase ketertarikan (confindence) pelanggan terhadap produk yang ditawarkan.

Terdapat 2 bagian dalam Association Rules :

- Antecedent (if)
- Consequent (then)

Antecedent merupakan sesuatu yang ditemukan di dalam data, dan Consequent adalah item yang ditemukan di dalam hubungannya dengan Antecedent. 

Contoh nya seperti aturan berikut:
"70% dari orang-orang yang membeli mie, juice dan saus akan membeli juga roti tawar".

# Association Rules Mining : Metrik Evaluasi

<b>Metrik evaluasi dalam Association Rule Mining adalah sebagai berikut :

- Support (s) => Ini adalah jumlah transaksi yang menyertakan item dari {X} dan {Y} bagian aturan sebagai persentase dari total transaksi. Ini dapat direpresentasikan dalam bentuk persentase dari semua transaksi yang menunjukkan seberapa sering sekelompok item terjadi bersama-sama.

Support = σ(X+Y) ÷ total => Ini adalah pecahan dari transaksi yang mencakup X dan Y.


- Confidence(c) => Rasio ini menunjukkan jumlah total transaksi semua item di {A} dan {B} dengan jumlah transaksi item di {A}.

Conf(X=>Y) = Supp(X∪Y) Supp(X) => Menghitung berapa kali setiap item di Y muncul dalam transaksi yang juga menyertakan item di X.


- Lift(l) => Kenaikan aturan X=>Y adalah kepercayaan aturan dibagi dengan kepercayaan yang diharapkan. di sini, diasumsikan bahwa itemset X dan Y independen satu sama lain. Keyakinan yang diharapkan dihitung dengan membagi keyakinan dengan frekuensi {Y}.

Lift(X=>Y) = Conf(X=>Y) Supp(Y) => Nilai lift yang mendekati 1 menunjukkan bahwa X dan Y hampir selalu muncul bersamaan seperti yang diharapkan. Nilai peningkatan lebih besar dari 1 menunjukkan bahwa mereka muncul bersama lebih dari yang diharapkan, dan nilai peningkatan kurang dari 1 menunjukkan bahwa mereka muncul kurang dari yang diharapkan. Nilai peningkatan yang lebih besar menunjukkan asosiasi yang lebih kuat.

# Beberapa penerapan Association Rule Mining
Terdapat beberapa penerapan Association Rule Mining yaitu :
- Market-Based Analysis
- Medical Diagnosis
- Census Data

# Algorithms of Association Rule Mining
Beberapa algoritma yang dapat digunakan untuk menghasilkan Association Rule M:

<b>1. Apriori Algorithm
   
Algoritma ini menggunakan kumpulan data yang sering digunakan untuk menghasilkan association rules. Algoritma ini dirancang untuk bekerja pada database yang berisi transaksi Algoritma Apriori mengidentifikasi item individual yang sering muncul dalam database dan kemudian mengembangkannya ke set item yang lebih besar, dengan tetap memeriksa bahwa set item cukup sering muncul dalam database.
    
<b>2. Eclat Algorithm(Equivalent Class Transformation)
    
Algoritma ECLAT dikenal juga sebagai Equivalence Class Clustering. Algoritma ini menggunakan teknik depth-first search untuk menemukan frequent itemset dalam database transaksi. Ia melakukan eksekusi lebih cepat daripada Algoritma Apriori sehingga beberapa orang menganggapnya sebagai versi yang lebih baik dan lebih efisien dari algoritma Apriori.
    
<b>3. F-P Algorithm(Frequent Pattern)
    
F-P Algorithm dikenal juga sebagai pola berulang. Algoritma Ini adalah versi perbaikan dari Algoritma Apriori. Ini adalah versi perbaikan dari Algoritma Apriori. Ini mewakili database dalam bentuk struktur pohon yang dikenal sebagai pola atau pohon yang sering. Ini mewakili database dalam bentuk struktur pohon yang dikenal sebagai frequent pattern atau frequent tree. Tujuan dari frequent tree ini adalah untuk mengekstrak pola yang paling sering.

# Implementasi Association Rule Mining

### *implementasi menggunakan apriori*

In [1]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/Bepe09/Exercise-Week-9/main/Retail%20Online.csv", header=None, sep=",")
data.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,soup,light cream,shallot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,frozen vegetables,spaghetti,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,french fries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,eggs,pet food,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,cookies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data = data.fillna(" ")
data.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,,,,,,,,,,,,,,,,,
2,chutney,,,,,,,,,,,,,,,,,,,
3,turkey,avocado,,,,,,,,,,,,,,,,,,
4,mineral water,milk,energy bar,whole wheat rice,green tea,,,,,,,,,,,,,,,
5,soup,light cream,shallot,,,,,,,,,,,,,,,,,
6,frozen vegetables,spaghetti,green tea,,,,,,,,,,,,,,,,,
7,french fries,,,,,,,,,,,,,,,,,,,
8,eggs,pet food,,,,,,,,,,,,,,,,,,
9,cookies,,,,,,,,,,,,,,,,,,,

In [4]:
list_data = set()
for i in data:
    if data[i].unique != " " :
        list_data.update(data[i].unique())
print(list_data)

{'tomatoes', 'shrimp', 'spaghetti', 'shallot', 'mineral water', 'turkey', 'cookies', 'yams', 'fresh tuna', 'milk', 'sparkling water', 'antioxydant juice', 'extra dark chocolate', 'shampoo', 'soup', 'olive oil', 'oil', 'salmon', 'black tea', 'red wine', 'almonds', 'spinach', 'chocolate', 'pet food', 'french fries', 'green tea', 'vegetables mix', 'meatballs', 'honey', 'green grapes', 'protein bar', 'cottage cheese', 'frozen smoothie', 'salad', 'eggs', 'frozen vegetables', ' ', 'light cream', 'chicken', 'cooking oil', 'tomato juice', 'chutney', 'energy bar', 'whole weat flour', 'burgers', 'pepper', 'whole wheat rice', 'energy drink', 'avocado', 'champagne', 'low fat yogurt', 'rice', 'pasta'}

In [5]:
set_list = set(list_data)
encoded = []
for i, j in data.iterrows():
    rowset = set(j) 
    labels = {}
    uncommons = list(set_list - rowset)
    commons = list(set_list.intersection(rowset))
    for k in uncommons:
        labels[k] = 0
    for z in commons:
        labels[z] = 1
    encoded.append(labels)
encoded[0]
df = pd.DataFrame(encoded)

In [6]:
df_banyak = apriori(df, min_support=0.2, use_colnames=True, verbose=1)
df_banyak

Processing 6 combinations | Sampling itemset size 3

D:\Aplikasi\Anaconda\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

   support            itemsets
0     0.20            (turkey)
1     0.30              (eggs)
2     0.95                 ( )
3     0.30     (mineral water)
4     0.20         (turkey,  )
5     0.30           ( , eggs)
6     0.25  (mineral water,  )

In [7]:
dr_ar = association_rules(df_banyak, metric="confidence", min_threshold=0.6)
dr_ar.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(turkey),( ),0.2,0.95,0.20,1.000000,1.052632,0.010,inf
1,(eggs),( ),0.3,0.95,0.30,1.000000,1.052632,0.015,inf
2,(mineral water),( ),0.3,0.95,0.25,0.833333,0.877193,-0.035,0.3

# Conclusion

Association rule sangat berguna dalam menganalisis kumpulan data. Data dikumpulkan menggunakan Qr Code Scanner di supermarket. Basis data tersebut terdiri dari sejumlah besar catatan transaksi yang mencantumkan semua item yang dibeli oleh pelanggan dalam sekali pembelian. Jadi manajer dapat mengetahui jika kelompok barang tertentu secara konsisten dibeli bersama dan menggunakan data ini untuk menyesuaikan tata letak toko, penjualan silang, promosi berdasarkan statistik.

### Hasil dari penggunaan Association Rule Mining
Dengan menggunakan Association Rule Mining, Dapat mengetahui seberapa sering jika barang A dan B dibeli secara bersamaan oleh customer. Dengan begitu dapat disimpulkan untuk mengambil strategi untuk lebih meningkatkan penjualan seperti:

- Dengan menggabungkan atau meletakkan kedua produk bersebelahan akan semakin meningkatkan daya beli customer.
- Memberikan penawaran jika customer membeli kedua produk secara bersamaan maka akan mendapat diskon khusus.

Reference :
- Fauzy, M., Rahmat, K., & Asror, I.. (2015). Penerapan Metode Association Rule Menggunakan Algoritma Apriori pada Simulasi Prediksi Hujan Wilayah Kota Bandung. e-Proceeding of Engineering, 2(3), 1-6. Diakses dari https://core.ac.uk/download/pdf/299905763.pdf
- Lutkevich, B. (n.d.). Association Rules. Diakses dari https://www.techtarget.com/searchbusinessanalytics/definition/association-rules-in-data-mining
- Rinto Rante Rerung. (2018). Penerapan Data Mining dengan Memanfaatkan Metode Association Rule untuk Promosi Produk. Diakses dari https://www.neliti.com/publications/259801/penerapan-data-mining-dengan-memanfaatkan-metode-association-rule-untuk-promosi#:~:text=Dalam%20bidang%20keilmuan%20data%20mining,sering%20dibeli%20oleh%20palanggan%20tersebut.
- IlmuSkripsi. (n.d). Association Rules. Diakses dari https://www.ilmuskripsi.com/2016/06/association-rules.html#:~:text=Association%20rule%20mining%20adalah%20analisa,akan%20membeli%20juga%20roti%20tawar%22.
- Jena, M. (2022). Association Rule Mining Simplified 101. Diakses dari https://hevodata.com/learn/association-rule-mining/#a2
- sourceilmuinformatika. (2019). Asosiasi Data dengan Algoritma Apriori menggunakan Python. Diakses dari https://kuliahtif.wordpress.com/2019/12/17/asosiasi-data-dengan-algoritma-apriori-menggunakan-python/
- Hafizhan Aliady Afif. (2018). Market Basket Analysis Menggunakan— python. Diakses dari https://medium.com/@hafizhan.aliady/market-basket-analysis-acossiation-rule-menggunakan-python-1012f9e1611d
- Alind, G. (n.d.). Implementing Apriori algorithm in Python. Diakses dari https://www.geeksforgeeks.org/implementing-apriori-algorithm-in-python/
- Fauzan, F. (2022). Penerapan Algoritma Apriori : Contoh dan Implementasi menggunakan Python. Diakses dari https://www.codekop.com/read/penerapan-algoritma-apriori-contoh-dan-implementasi-menggunakan-python-68.html
- Chonyy. (2020). Apriori — Association Rule Mining In-depth Explanation and Python Implementation. Diakses dari https://towardsdatascience.com/apriori-association-rule-mining-explanation-and-python-implementation-290b42afdfc6